# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Đẩy hình ảnh Docker vào nhiều cơ quan đăng ký
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Kiểm tra repo
        uses: actions/checkout@v3

      - name: Đăng nhập vào Trung tâm Docker
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Đăng nhập vào sổ đăng ký Container
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Trích xuất siêu dữ liệu (thẻ, nhãn) cho Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            n3d1117/chatgpt-telegram-bot
            ghcr.io/${{ github.repository }}

      - name: Xây dựng và đẩy hình ảnh Docker
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
